# Generated by Django 3.1.2 on 2020-11-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_auto_20201118_1619'),
        ('applications', '0003_auto_20201118_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
