version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: zhan9san/devops-tool-web:${DEVOPS_TOOL_WEB_VERSION:-latest}
    command: gunicorn DevOpsTool.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: ./nginx
    image: zhan9san/devops-tool-nginx:${DEVOPS_TOOL_NGINX_VERSION:-latest}
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    env_file:
      - ./.env.prod
    depends_on:
      - web

volumes:
  static_volume:
