# Generated by Django 3.1.2 on 2020-11-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('package', models.CharField(max_length=200)),
                ('ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('jenkins_build_url', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('package', models.CharField(max_length=200)),
                ('ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('jenkins_build_url', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
