# Generated by Django 3.1.2 on 2020-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='jenkins_build_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latestpackage',
            name='jenkins_build_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
