# Generated by Django 3.1.2 on 2020-11-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('applications', '0002_auto_20201117_0743'),
        ('deployments', '0002_auto_20201117_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestPackage',
            new_name='CurrentPackage',
        ),
    ]
